### ISSUE TITLE
Handler when Screenshotlayer API does not connect

### ISSUE THREAD

**Issue by jasonm** [adriangoe/wagtailvisualdiff#1]
Hi @adriangoe !

It looks like it's possible for the `process_page_published` task to fail when the screenshotlayer.com API refuses to connect.  The code correctly handles the case where the screenshotlayer.com API returns a 500, but does not handle a lower-level socket disconnect (e.g. if screenshotlayer.com API is entirely down, perhaps for brief maintenance).

Stacktrace:

``` python
#4 File "/home/ubuntu/schools_env/src/wagtailvisualdiff/wagtailvisualdiff/screenshot.py" line 59 in process_page_published
prs.mobile_screenshot.save(str(revision.id) + "_mobile.png", ContentFile(fp2.read()))

#5 File "/usr/lib/python2.7/socket.py" line 351 in read
data = self._sock.recv(rbufsize)

#6 File "/usr/lib/python2.7/ssl.py" line 341 in recv
return self.read(buflen)

#7 File "/usr/lib/python2.7/ssl.py" line 260 in read
return self._sslobj.read(len)

error: [Errno 104] Connection reset by peer
```

A couple options to handle this could include:
1. Handle this particular error http://stackoverflow.com/a/20568874 (and maybe more errors similar to it?  I'm not sure what would be the ideal scope of exceptions to catch)
2. Modify the Celery task to retry - [Celery docs on retrying](http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying)

**Comment by jasonm** [comment]
Internal Rollbar tracking: https://rollbar.com/minervaproject/Schools/items/13058/

**Comment by adriangoe** [comment]
@jasonm thanks for catching that! https://github.com/adriangoe/wagtailvisualdiff/commit/5f25e041d8df3dd53b2ca8b1b69e466485c53c4c should fix this!
